name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Display Message
        run: echo "Building Application"

      - name: Run Tests
        run: echo "Testing Successful"

      - name: Deploy
        run: echo "Deployment Successful"